config:
  property: default
spring:
  jpa:
    database: postgresql
    show-sql: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://192.168.1.80:5432/eagle_eye_dev
    driver-class-name: org.postgresql.Driver

